# Site settings
title: Brian Boyko
email: brian.boyko@gmail.com
description: "Blog of Brian Boyko, full-stack software engineer."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "brianboyko.github.io" # the base hostname & protocol for your site
twitter_username: boyko4tx
github_username:  brianboyko
excerpt_separator: "<!-- break -->"
# Build settings
markdown: kramdown
